---
- hosts: all
  remote_user: vagrant
  vars:
  - ansible_python_interpreter: /usr/local/bin/python2.7
  tasks:
  - name: upgrade pkg
    raw: sudo pkg upgrade -y
  - name: upgrade python27
    pkgng: name=python27 state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: install vim-lite
    pkgng: name=vim-lite state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: install git
    pkgng: name=git state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: clone crochet
    git: repo=https://github.com/freebsd/crochet
         dest=/home/vagrant/crochet
         version=master
  - name: copy config.rpi2.sh
    copy: src=./config.rpi2.sh
          dest=/home/vagrant/crochet/config.rpi2.sh
          owner=vagrant
          group=vagrant
          mode="u=rw,g=r,o=r"
  - name: copy config.rpi2.canakit.sh
    copy: src=./config.rpi2.canakit.sh
          dest=/home/vagrant/crochet/config.rpi2.canakit.sh
          owner=vagrant
          group=vagrant
          mode="u=rw,g=r,o=r"
  - name: copy config.cuboxi.sh
    copy: src=./config.cuboxi.sh
          dest=/home/vagrant/crochet/config.cuboxi.sh
          owner=vagrant
          group=vagrant
          mode="u=rw,g=r,o=r"
  - name: install u-boot-rpi2
    pkgng: name=sysutils/u-boot-rpi2 state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: clone svn repo in /home/vagrant/crochet/src
    subversion: repo=svn://svn.freebsd.org/base/head
                dest=/home/vagrant/crochet/src
                executable=/usr/bin/svnlite
                revision=HEAD
                switch=no
                force=yes
